### ISSUE TITLE
running "ver" first time

### ISSUE THREAD

**Issue by arturmartins** [mysz/versionup#1]
Hi,

Installed: 
pip install versionner

After I run:
ver

Output:
Traceback (most recent call last):
  File "/usr/local/bin/ver", line 7, in <module>
    from versionner import main
  File "/usr/local/lib/python2.7/site-packages/versionner.py", line 283
    print("Incorrect configuration for file \"%s\": %s" % (project_file.filename, ex.args[0]), file=sys.stderr)
                                                                                                   ^
SyntaxError: invalid syntax

shouldn't I get a usage help message instead?

**Comment by msztolcman** [comment]
Hm, my mistake - I didn't write that tool is written only for Python 3.3+. I'll try also set something in setup.py to tell pip that it works only with fixed versions of Python (as I see, specifiers are not enough).
Anyway, I will update documentation soon.

> shouldn't I get a usage help message instead?

And with Py3.3 it doesn't fail - it show current project version instead of project or at least short message:

```
% ver
Version file not found
```

**Comment by msztolcman** [comment]
I don't find simple way to tell pip that tool works only with version 3.3+, so I created some workarounds for this. Now (1.1.1) the tool and setup.py make test for python versions and display info about Python version, so this should never happen again.
However, please reopen ticket if it does.
